[2022-10-07T16:15:51.163+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tek_distribuidora.colector manual__2022-10-07T16:15:47.003188+00:00 [queued]>
[2022-10-07T16:15:51.172+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tek_distribuidora.colector manual__2022-10-07T16:15:47.003188+00:00 [queued]>
[2022-10-07T16:15:51.173+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T16:15:51.174+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-07T16:15:51.174+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-07T16:15:51.190+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-10-07 16:15:47.003188+00:00
[2022-10-07T16:15:51.195+0000] {standard_task_runner.py:54} INFO - Started process 2363 to run task
[2022-10-07T16:15:51.198+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tek_distribuidora', 'colector', 'manual__2022-10-07T16:15:47.003188+00:00', '--job-id', '432', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl89ulsm_']
[2022-10-07T16:15:51.198+0000] {standard_task_runner.py:83} INFO - Job 432: Subtask colector
[2022-10-07T16:15:51.199+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-10-07T16:15:51.731+0000] {task_command.py:384} INFO - Running <TaskInstance: tek_distribuidora.colector manual__2022-10-07T16:15:47.003188+00:00 [running]> on host 9a36b0424536
[2022-10-07T16:15:51.803+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tek_distribuidora
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-10-07T16:15:47.003188+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-07T16:15:47.003188+00:00
[2022-10-07T16:15:51.804+0000] {tasks.py:39} INFO - Defining DEC to export information
[2022-10-07T16:15:51.811+0000] {tasks.py:360} INFO - Reading prep dataframe
[2022-10-07T16:15:51.830+0000] {tasks.py:153} INFO - Instantiating the Browser with the requested settings
[2022-10-07T16:16:03.314+0000] {tasks.py:167} INFO - Browser configured
[2022-10-07T16:16:03.315+0000] {tasks.py:290} INFO - Removing nan URL values
[2022-10-07T16:16:03.317+0000] {tasks.py:291} INFO - Requested prices before: 0
[2022-10-07T16:16:03.321+0000] {tasks.py:296} INFO - Requested prices after: 0
[2022-10-07T16:16:03.322+0000] {tasks.py:417} INFO - Saved screenshots and prices
[2022-10-07T16:16:03.322+0000] {tasks.py:248} INFO - Test passed
[2022-10-07T16:16:03.325+0000] {tasks.py:274} INFO - Requested prices: 0
[2022-10-07T16:16:03.326+0000] {tasks.py:275} INFO - Scraped prices: 0
[2022-10-07T16:16:03.326+0000] {tasks.py:276} INFO - Day of the scraping: 07/10/2022
[2022-10-07T16:16:03.328+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 419, in colector
    dataframe=dataframe, price=price, url=url, shipping=shipping, date=date, path=path
  File "/opt/airflow/dags/tasks.py", line 279, in append_encomenda
    resultado_coleta, left_on="URL DO INSUMO", right_on="url_coleta", how="left"
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9203, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 119, in merge
    validate=validate,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1256, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat
[2022-10-07T16:16:03.397+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=tek_distribuidora, task_id=colector, execution_date=20221007T161547, start_date=20221007T161551, end_date=20221007T161603
[2022-10-07T16:16:03.479+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 432 for task colector (You are trying to merge on object and float64 columns. If you wish to proceed you should use pd.concat; 2363)
[2022-10-07T16:16:03.579+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-07T16:16:03.637+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
