[2022-09-30T15:35:02.617+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: casa_das_ferragens.colector manual__2022-09-30T15:34:18.697065+00:00 [queued]>
[2022-09-30T15:35:02.625+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: casa_das_ferragens.colector manual__2022-09-30T15:34:18.697065+00:00 [queued]>
[2022-09-30T15:35:02.625+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-30T15:35:02.625+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-30T15:35:02.626+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-30T15:35:02.636+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): colector> on 2022-09-30 15:34:18.697065+00:00
[2022-09-30T15:35:02.641+0000] {standard_task_runner.py:54} INFO - Started process 165 to run task
[2022-09-30T15:35:02.643+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'casa_das_ferragens', 'colector', 'manual__2022-09-30T15:34:18.697065+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpn8woo6iv']
[2022-09-30T15:35:02.643+0000] {standard_task_runner.py:83} INFO - Job 325: Subtask colector
[2022-09-30T15:35:02.644+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-09-30T15:35:03.021+0000] {task_command.py:384} INFO - Running <TaskInstance: casa_das_ferragens.colector manual__2022-09-30T15:34:18.697065+00:00 [running]> on host dc20523c063c
[2022-09-30T15:35:03.082+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=casa_das_ferragens
AIRFLOW_CTX_TASK_ID=colector
AIRFLOW_CTX_EXECUTION_DATE=2022-09-30T15:34:18.697065+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-30T15:34:18.697065+00:00
[2022-09-30T15:35:03.083+0000] {tasks.py:39} INFO - Defining DEC to export information
[2022-09-30T15:35:03.087+0000] {tasks.py:343} INFO - Reading prep dataframe
[2022-09-30T15:35:03.094+0000] {tasks.py:146} INFO - Instantiating the Browser with the requested settings
[2022-09-30T15:35:04.332+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks.py", line 345, in colector
    browser = config_browser(config)
  File "/opt/airflow/dags/tasks.py", line 149, in config_browser
    desired_capabilities=config["browser_arg"])
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available

[2022-09-30T15:35:04.344+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=casa_das_ferragens, task_id=colector, execution_date=20220930T153418, start_date=20220930T153502, end_date=20220930T153504
[2022-09-30T15:35:04.356+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 325 for task colector (Message: Requested environment is not available
; 165)
[2022-09-30T15:35:04.380+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-30T15:35:04.404+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
