[2022-10-03T12:08:22.891+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: agrobombas.prep scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-03T12:08:22.904+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: agrobombas.prep scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-03T12:08:22.905+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-03T12:08:22.905+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-03T12:08:22.905+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-03T12:08:22.919+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): prep> on 2022-09-01 00:00:00+00:00
[2022-10-03T12:08:22.923+0000] {standard_task_runner.py:54} INFO - Started process 1697 to run task
[2022-10-03T12:08:22.925+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'agrobombas', 'prep', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdwewacqv']
[2022-10-03T12:08:22.925+0000] {standard_task_runner.py:83} INFO - Job 364: Subtask prep
[2022-10-03T12:08:22.927+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag.py
[2022-10-03T12:08:23.833+0000] {dagbag.py:330} ERROR - Failed to import: /opt/***/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 30, in <module>
    configs = yaml.safe_load(file)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/airflow/.local/lib/python3.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/opt/airflow/dags/config.yaml", line 10, column 11
expected <block end>, but found ','
  in "/opt/airflow/dags/config.yaml", line 10, column 33
[2022-10-03T12:08:23.841+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 364 for task prep (Dag 'agrobombas' could not be found; either it does not exist or it failed to parse.; 1697)
[2022-10-03T12:08:23.861+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-03T12:08:23.885+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
